Fixing regex for dirnames capitalized
IcaliaLabs/plis pull request #22
Opened 2019-04-18 02:05 UTC by alvadorn

### What does this PR do?

* Fix regex on directory names capitalized

Like referenced on issue #19, the latest release of `plis` can't attach containers on directories which its name are capitalized, for example: 

- `BACK-END-3`,  docker-compose uses `back-end-3` as namespace but the current regex looks for `BACK-END-3`

2019-04-26 16:34 UTC, gabrielsclimaco commented
+1

2019-05-09 15:55 UTC, vovimayhem requested changes
Hi @alvadorn ! Thanks for your interest in `plis` :)

For the sake of clarity and purpose of the variables used in this method, I propose the following changes to the code in your PR:

1: leave `dirName` as it was prior to this PR:

```go
            dirName := filepath.Base(currentWorkdir)
```

2: Add a new variable `containerName`:
```go
        containerName := strings.ToLower(dirName + "_" + serviceName)
```

3: Use `containerName` in the regexPattern: (My bad... `rp` stands for "Regex Pattern" here... will correct that in another PR!)
```go
      rp := regexp.MustCompile("^" + containerName + "_\\d+") 
```

Thanks for your PR! I'll just use a Willem Dafoe gif 'cause it's soo damn friggin' cool: 
![Keep em coming](https://media.giphy.com/media/n6xe7RntgjFyo/giphy.gif)

2019-05-09 19:18 UTC, alvadorn commented
Totally agreed with your review. Fix pushed.

2019-05-09 23:30 UTC, vovimayhem approved these changes

2019-05-09 23:32 UTC, merged

2019-05-09 23:37 UTC, vovimayhem commented
Thanks @alvadorn ! I'll try to cut a release tomorrow!